# Generated by Django 3.1.2 on 2020-10-14 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_integraciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adjudicacionitem',
            old_name='organismo',
            new_name='organismo_proveedor',
        ),
        migrations.AddField(
            model_name='licitacion',
            name='informada',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='licitacion',
            name='moneda',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Moneda',
        ),
    ]
