# Generated by Django 3.1.2 on 2020-10-26 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_integraciones', '0004_itemlicitacion_licitacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcesoExtraccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='LicitacionRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo_estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_cierre', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('datos_json', models.TextField(blank=True, default='')),
                ('esta_completa', models.BooleanField(default=False)),
                ('esta_en_bd', models.BooleanField(default=False)),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_integraciones.procesoextraccion')),
            ],
        ),
        migrations.CreateModel(
            name='LicitacionChecklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('licitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend_integraciones.licitacion')),
            ],
        ),
    ]
