# Generated by Django 3.1.2 on 2020-10-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_integraciones', '0005_licitacionchecklist_licitacionrequest_procesoextraccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoextraccion',
            name='historico',
            field=models.BooleanField(default=False),
        ),
    ]
