# Generated by Django 3.1.2 on 2020-10-27 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_integraciones', '0007_licitacionchecklist_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licitacionchecklist',
            name='licitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend_integraciones.licitacion'),
        ),
    ]
