# Generated by Django 3.1.2 on 2020-10-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_integraciones', '0008_auto_20201027_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='procesoextraccion',
            name='fecha_licitaciones',
            field=models.CharField(default='', max_length=50),
        ),
    ]
